Repository mcci-catena/Catena4430_Sensor, pull requests merged in 2024-04, with the labels that each got.

#25 added feature to rejoin and fixed missing comma for SD card data
  Catena4430_Sensor.ino
  Catena4430_cMeasurementLoop.cpp
  Catena4430_cMeasurementLoop.h
  Catena4430_cMeasurementLoopV1.cpp
  Catena4430_cMeasurementLoopV2.cpp
  Catena4430_cMeasurementLoop_SDcard.cpp
Labels: bug, enhancement

#27 fix #26: added watchdog to perform reset on hang
  Catena4430_Sensor.ino
  Catena4430_cMeasurementLoop.cpp
  Catena4430_cMeasurementLoop.h
  Catena4430_cMeasurementLoopV1.cpp
  Catena4430_cMeasurementLoopV2.cpp
  Catena4430_cmd.h
  cmdHang.cpp
Labels: enhancement

#29 Fix #28: Added refresh watchdog timer during FW update via SD card
  Catena4430_Sensor.ino
  Catena4430_cMeasurementLoop.cpp
  Catena4430_cMeasurementLoop.h
  Catena4430_cMeasurementLoopV1.cpp
  Catena4430_cMeasurementLoopV2.cpp
  Catena4430_cMeasurementLoop_SDcard.cpp
Labels: bug
